### ISSUE TITLE
sft_vlm训练了一个epoch报错，求助大佬，还有数据集的<image>\n有啥用，为啥有的在前有的在后啊

### ISSUE THREAD

**Issue by huskyth** [jingyaogong/minimind-v#21]
Traceback (most recent call last):
  File "/kaggle/working/minimind-v/2-sft_vlm.py", line 266, in <module>
    train_epoch(epoch, wandb)
  File "/kaggle/working/minimind-v/2-sft_vlm.py", line 64, in train_epoch
    logits = model(X, Y, image_encoders=image_encoders).logits
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/minimind-v/model/model.py", line 435, in forward
    h = self.count_vision_proj(tokens=tokens, h=h, image_encoders=image_encoders, seqlen=seqlen)
  File "/kaggle/working/minimind-v/model/model.py", line 411, in count_vision_proj
    h[i] = torch.cat((before, vision_proj[i][img_idx], after), dim=0)[:seqlen]

**Comment by xinyanghuang7** [comment]
非常抱歉给您造成困扰。

请问你使用的是最新上传的代码吗？
第[398行](https://github.com/jingyaogong/minimind-v/blob/master/model/model.py#L398)的内容和现有仓库是对应的吗？

如readme中所说，”VLM的输入依然是一段文本，其中包含特殊的占位符。 在计算文本嵌入后，可以将图像编码器生成的向量投影到该占位符对应的嵌入部分，替换掉原先的占位符embedding。“，这个特殊的占位符就是<image>，即图像token的位置。
